2025-10-17 05:33:05.428 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-10-17 05:33:05.433 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration kia_connect which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-10-17 05:33:08.507 ERROR (MainThread) [homeassistant.config] Setup of package 'evohome_climate_control' at packages/evohome_climate_control.yaml, line 7 failed: integration 'script' has duplicate key 'alias'
2025-10-17 05:33:08.508 ERROR (MainThread) [homeassistant.config] Setup of package 'smart_appliances' at packages/smart_appliances.yaml, line 7 failed: integration 'input_boolean' has duplicate key 'name'
2025-10-17 05:33:08.513 ERROR (MainThread) [homeassistant.config] Setup of package 'witgoed_dal_tarief' at packages/witgoed_dal_tarief.yaml, line 4 failed: Integration 'witgoed_dal_tarief' not found.
2025-10-17 05:33:08.517 ERROR (MainThread) [homeassistant.config] Setup of package 'witgoed_dashboard' at packages/witgoed_dashboard.yaml, line 4 failed: Integration 'witgoed_management' not found.
2025-10-17 05:33:14.215 ERROR (MainThread) [homeassistant.helpers.translation] Validation of translation placeholders for localized (nl) string component.homeassistant_sky_connect.options.progress.install_firmware failed: ({'firmware_name', 'model'} != {'firmware_name'})
2025-10-17 05:33:14.223 ERROR (MainThread) [homeassistant.helpers.translation] Validation of translation placeholders for localized (nl) string component.homeassistant_sky_connect.config.progress.install_firmware failed: ({'firmware_name', 'model'} != {'firmware_name'})
2025-10-17 05:33:41.971 ERROR (MainThread) [homeassistant.config] Setup of package 'evohome_climate_control' at packages/evohome_climate_control.yaml, line 7 failed: integration 'script' has duplicate key 'alias'
2025-10-17 05:33:41.972 ERROR (MainThread) [homeassistant.config] Setup of package 'smart_appliances' at packages/smart_appliances.yaml, line 7 failed: integration 'input_boolean' has duplicate key 'name'
2025-10-17 05:33:41.979 ERROR (MainThread) [homeassistant.config] Setup of package 'witgoed_dal_tarief' at packages/witgoed_dal_tarief.yaml, line 4 failed: Integration 'witgoed_dal_tarief' not found.
2025-10-17 05:33:41.983 ERROR (MainThread) [homeassistant.config] Setup of package 'witgoed_dashboard' at packages/witgoed_dashboard.yaml, line 4 failed: Integration 'witgoed_management' not found.
2025-10-17 05:33:47.155 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/fritzconnection/core/soaper.py:207: SyntaxWarning: invalid escape sequence '\d'
  wifi_pwd_keys = 'New(WEPKey\d+|PreSharedKey|KeyPassphrase)'

2025-10-17 05:33:59.737 ERROR (MainThread) [homeassistant.components.sensor] Error adding entity sensor.kriebb_homeassistant_laatste_commit for domain sensor with platform github
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 676, in _async_add_entities
    await self._async_add_entity(
        entity, False, entity_registry, config_subentry_id
    )
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 1002, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1382, in add_to_platform_finish
    self.async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1026, in async_write_ha_state
    self._async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1151, in _async_write_ha_state
    self.__async_calculate_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1088, in __async_calculate_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1032, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 569, in state
    value = self.native_value
            ^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/github/sensor.py", line 194, in native_value
    return self.entity_description.value_fn(self.coordinator.data)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/github/sensor.py", line 81, in <lambda>
    value_fn=lambda data: data["default_branch_ref"]["commit"]["message"][:255],
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2025-10-17 05:34:16.157 WARNING (MainThread) [homeassistant.components.homeassistant.triggers.numeric_state] Error initializing 'Wasmachine Cyclus Detectie' trigger: In 'numeric_state' condition: unknown entity sensor.wasmachine_power
2025-10-17 05:34:16.158 WARNING (MainThread) [homeassistant.components.homeassistant.triggers.numeric_state] Error initializing 'Wasmachine Cyclus Detectie' trigger: In 'numeric_state' condition: unknown entity sensor.wasmachine_power
2025-10-17 05:36:16.180 ERROR (MainThread) [homeassistant.components.automation.evohome_refresh_on_ha_start] Evohome: Refresh on HA Start: Error executing script. Service not found for call_service at pos 2: Action evohome.refresh_system not found
2025-10-17 05:47:19.847 WARNING (MainThread) [homeassistant.components.mqtt.client] Error returned from MQTT server: The connection was lost.
2025-10-17 05:47:42.836 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /addons/core_samba/info - System is not ready with state: shutdown
2025-10-17 05:47:46.457 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /addons/a0d7b954_vscode/info - System is not ready with state: shutdown
